### ISSUE TITLE
Upgrade to semantic-release v23

### ISSUE THREAD

**Issue by AntoninoBonanno** [semantic-release/wordpress#229]
### New feature motivation

npm ERR! Could not resolve dependency:
npm ERR! peer semantic-release@"^21.0.7 || ^22.0.0" from @semantic-release/wordpress@1.6.1
npm ERR! node_modules/@semantic-release/wordpress
npm ERR!   dev @semantic-release/wordpress@"^1.6.1" from the root project

### New feature description

Close #212

**Comment by seebeen** [comment]
Done - and done
